name: irmamobile
description: IRMA Authentication

# A build number cannot be reused once a build is in use on Android.
version: 7.5.0+4194463

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sentry_flutter: ^6.22.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_svg: ^2.0.7
  flutter_i18n: ^0.33.0
  flutter_bloc: ^7.2.0
  equatable: ^2.0.3
  email_validator: ^2.0.1
  url_launcher: ^6.0.10
  json_annotation: ^4.8.0
  rxdart: ^0.27.2
  package_info: ^2.0.2
  collection: ^1.15.0
  qr_code_scanner: ^1.0.1
  native_device_orientation: ^1.1.4
  share: ^2.0.4
  intl: ^0.18.0
  flutter_markdown: ^0.6.6
  shared_preferences: ^2.0.7
  async: ^2.6.1
  streaming_shared_preferences: ^2.0.0
  flutter_jailbreak_detection: ^1.10.0
  visibility_detector: ^0.2.2
  quiver: ^3.0.1
  flutter_privacy_screen: 1.3.0
  timeline_tile: ^2.0.0
  lottie: ^1.4.2
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.1
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.3.1
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  image: assets/non-free/logo_payoff.png
  color: "F7F7F7"
  android_disable_fullscreen: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/non-free/app_icon.png"
  adaptive_icon_foreground: "assets/non-free/app_icon_foreground.png"
  adaptive_icon_background: "#FFFFFF"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/locales/
    - assets/arrow_back/
    - assets/enrollment/
    - assets/error/
    - assets/help/
    - assets/help/mobile_login/
    - assets/help/computer_login/
    - assets/reset/
    - assets/non-free/
    - assets/disclosure/
    - assets/ui/
    - assets/success/

  fonts:
    - family: Alexandria
      fonts:
        - asset: fonts/alexandria/Alexandria-Thin.ttf
          weight: 100
        - asset: fonts/alexandria/Alexandria-ExtraLight.ttf
          weight: 200
        - asset: fonts/alexandria/Alexandria-Light.ttf
          weight: 300
        - asset: fonts/alexandria/Alexandria-Regular.ttf
          weight: 400
        - asset: fonts/alexandria/Alexandria-Medium.ttf
          weight: 500
        - asset: fonts/alexandria/Alexandria-SemiBold.ttf
          weight: 600
        - asset: fonts/alexandria/Alexandria-Bold.ttf
          weight: 700
        - asset: fonts/alexandria/Alexandria-ExtraBold.ttf
          weight: 800
        - asset: fonts/alexandria/Alexandria-Black.ttf
          weight: 900
    - family: Open Sans
      fonts:
        - asset: fonts/open-sans/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/open-sans/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/open-sans/OpenSans-Medium.ttf
          weight: 500
        - asset: fonts/open-sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/open-sans/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/open-sans/OpenSans-ExtraBold.ttf
          weight: 800
    - family: IrmaIcons
      fonts:
        - asset: fonts/irma-icons/IrmaIcons.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
