name: irmamobile
description: IRMA Authentication

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dots_indicator: ^1.0.0
  flutter_svg: ^0.14.1
  flutter_i18n: ^0.6.4
  flutter_bloc: ^0.21.0
  equatable: ^0.5.1
  email_validator: ^1.0.0
  webview_flutter: 0.3.14+1
  url_launcher: ^5.1.2
  json_serializable: ^3.2.0
  build_runner: ^1.6.6


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/locales/
    - assets/enrollment/
    - assets/icons/

  fonts:
    - family: Karla
      fonts:
        - asset: fonts/karla/Karla-Regular.ttf
        - asset: fonts/karla/Karla-RegularItalic.ttf
          style: italic
        - asset: fonts/karla/Karla-Bold.ttf
          weight: 700
        - asset: fonts/karla/Karla-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Medium.ttf
        - asset: fonts/montserrat/Montserrat-MediumItalic.ttf
          style: italic
        - asset: fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/montserrat/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
    - family: IrmaIcons
      fonts:
        - asset: fonts/irma-icons/IrmaIcons.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


