name: irmamobile
description: IRMA Authentication
version: 6.3.0+142

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sentry_flutter: ^6.13.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.5
  flutter_i18n: ^0.32.4
  flutter_bloc: ^7.2.0
  equatable: ^2.0.5
  email_validator: ^2.1.17
  url_launcher: ^6.1.6
  json_annotation: ^4.7.0
  rxdart: ^0.27.5
  package_info: ^2.0.2
  collection: ^1.16.0
  mobile_scanner: ^1.0.0
  native_device_orientation: ^1.1.4 # TODO: Remove this package once mobile_scanner supports landscape
  share: ^2.0.4
  intl: ^0.17.0
  flutter_markdown: ^0.6.12
  shared_preferences: ^2.0.15
  async: ^2.6.1
  streaming_shared_preferences: ^2.0.0
  path_drawing: ^1.0.1
  flutter_jailbreak_detection: ^1.8.0
  visibility_detector: ^0.3.3
  quiver: ^3.1.0
  privacy_screen: ^0.0.6
  dotted_decoration: ^2.0.0
  timeline_tile: ^2.0.0
  sliver_tools: ^0.2.8

flutter_native_splash:
  image: assets/non-free/logo_payoff.png
  color: "F7F7F7"
  android_disable_fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.5.3
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.12
  build_runner: ^2.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/locales/
    - assets/arrow_back/
    - assets/enrollment/
    - assets/error/
    - assets/help/
    - assets/help/mobile_login/
    - assets/help/computer_login/
    - assets/reset/
    - assets/non-free/
    - assets/disclosure/
  fonts:
    - family: Open Sans
      fonts:
        - asset: fonts/open-sans/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/open-sans/OpenSans-Medium.ttf
          weight: 500
        - asset: fonts/open-sans/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/open-sans/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/open-sans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
    - family: IrmaIcons
      fonts:
        - asset: fonts/irma-icons/IrmaIcons.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
