name: yivi
description: "Yivi App"

# A build number cannot be reused once a build is in use on Android.
version: 7.13.1+4194499

publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sentry_flutter: ^9.4.0
  yivi_core:
    path: ../yivi_core
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0
  camera: ^0.10.0+4
  smart_auth: ^3.2.0
  pinput: ^6.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # the following packages are required by the integrationt tests
  vcmrtd:
    git:
      url: https://github.com/privacybydesign/vcmrtd.git
      ref: v3.4.1
  package_info_plus: ^9.0.0
  collection: ^1.18.0
  flutter_riverpod: ^2.6.1
  rxdart: ^0.28.0
  mrz_parser:
    git:
      url: https://github.com/privacybydesign/mrz_parser
      ref: v3.0.0

flutter:
  uses-material-design: true
