name: yivi_core
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=3.3.0"

dependencies:
  plugin_platform_interface: ^2.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sentry_flutter: ^9.4.0
  go_router: ^16.0.0
  string_similarity: ^2.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_svg: ^2.0.7
  flutter_i18n: ^0.36.2
  flutter_bloc: ^7.2.0
  equatable: ^2.0.3
  email_validator: ^3.0.0
  url_launcher: ^6.0.10
  json_annotation: ^4.8.0
  rxdart: ^0.28.0
  package_info_plus: ^9.0.0
  collection: ^1.18.0
  qr_code_scanner_plus: ^2.0.10+1
  share_plus: 11.0.0
  intl: ^0.20.2
  flutter_markdown: ^0.7.4+1
  shared_preferences: ^2.0.7
  async: ^2.11.0
  streaming_shared_preferences: ^2.0.0
  visibility_detector: ^0.4.0+2
  quiver: ^3.0.1
  timeline_tile: ^2.0.0
  lottie: ^3.1.3
  permission_handler: ^12.0.1
  flutter_riverpod: ^2.6.1
  http: ^1.5.0
  mrz_parser:
    git:
      url: https://github.com/privacybydesign/mrz_parser
      ref: master
  google_mlkit_text_recognition: ^0.15.0
  camera: ^0.10.0+4
  google_mlkit_commons: ^0.11.0
  camera_platform_interface: ^2.2.2
  vcmrtd:
    git:
      url: https://github.com/privacybydesign/vcmrtd.git
      ref: v0.2.4
  mask_text_input_formatter: ^2.9.0
  jailbreak_root_detection: ^1.2.0+1
  # Temporary forks because their original repos are not compatible with new android api's.
  # Should be reverted back to their published version when they're made compatible.
  native_device_orientation:
    git:
      url: https://github.com/privacybydesign/flutter_native_device_orientation

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.14.1
  riverpod_lint: ^2.6.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: foundation.privacybydesign.yivi_core
        pluginClass: YiviCorePlugin
      ios:
        pluginClass: YiviCorePlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
